"""샘플 콘텐츠 — 지상파·PP 2025·2026 방영 드라마·예능.

참고: 각 방송사 편성 및 위키 드라마 목록(2025·2026년 대한민국의 텔레비전 드라마 목록).
채널: MBC, KBS1, KBS2, SBS, tvN, JTBC, ENA, 채널A, TV조선, MBN
"""

from datetime import date

# OTT 메타: 표시명, 브랜드 색, 로고 이니셜, 기본 검색/홈 URL 템플릿
# 로고는 외부 이미지 없이 인라인 이니셜 배지(추가 HTTP 0)로 표시한다.
OTT_META = {
    "넷플릭스": {
        "color": "#E50914",
        "letter": "N",
        "url": "https://www.netflix.com/kr/",
        "search": "https://www.netflix.com/search?q={query}",
    },
    "티빙": {
        "color": "#FF153C",
        "letter": "T",
        "url": "https://www.tving.com/",
        "search": "https://www.tving.com/search?keyword={query}",
    },
    "웨이브": {
        "color": "#1B1C3A",
        "letter": "W",
        "url": "https://www.wavve.com/",
        "search": "https://www.wavve.com/search?searchWord={query}",
    },
    "쿠팡플레이": {
        "color": "#E4002B",
        "letter": "C",
        "url": "https://www.coupangplay.com/",
        "search": "https://www.coupangplay.com/search?q={query}",
    },
    "디즈니+": {
        "color": "#113CCF",
        "letter": "D+",
        "url": "https://www.disneyplus.com/ko-kr",
        "search": "https://www.disneyplus.com/ko-kr/search?q={query}",
    },
    "왓챠": {
        "color": "#FF0558",
        "letter": "W",
        "url": "https://watcha.com/",
        "search": "https://watcha.com/search?query={query}",
    },
}

_PALETTES = [
    ("#1a1a2e", "#e94560"),
    ("#0f3460", "#16c79a"),
    ("#2d132c", "#ee4540"),
    ("#1b262c", "#3282b8"),
    ("#3d0000", "#950101"),
    ("#162447", "#e43f5a"),
    ("#0d7377", "#32e0c4"),
    ("#222831", "#00adb5"),
    ("#4a1942", "#c06c84"),
    ("#1f1f1f", "#f4a261"),
    ("#2c3e50", "#e74c3c"),
    ("#1a472a", "#6b8e23"),
]

# aired_at: 최근 방영 순 정렬용 (정규 예능은 최근 회차 기준일, 드라마는 첫방일)
CONTENTS = [
    # ========== 예능 (2026 방영 중 · 최근 회차) ==========
    {
        "id": "v01",
        "title": "런닝맨",
        "genre": "예능",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2026, 7, 19),
        "episode": "방영 중",
        "otts": [],
        "desc": "SBS 일요 예능. 미션·추리 버라이어티.",
    },
    {
        "id": "v02",
        "title": "나 혼자 산다",
        "genre": "예능",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2026, 7, 17),
        "episode": "방영 중",
        "otts": [],
        "desc": "MBC 금요 예능. 셀럽의 혼자 사는 일상.",
    },
    {
        "id": "v03",
        "title": "유 퀴즈 온 더 블럭",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 16),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 토크·거리 인터뷰 예능.",
    },
    {
        "id": "v04",
        "title": "전지적 참견 시점",
        "genre": "예능",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2026, 7, 12),
        "episode": "방영 중",
        "otts": [],
        "desc": "MBC 셀럽 관찰 예능.",
    },
    {
        "id": "v05",
        "title": "미운 우리 새끼",
        "genre": "예능",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2026, 7, 11),
        "episode": "방영 중",
        "otts": [],
        "desc": "SBS 일요 예능. 엄마와 아들 토크.",
    },
    {
        "id": "v06",
        "title": "아는 형님",
        "genre": "예능",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 7, 11),
        "episode": "방영 중",
        "otts": [],
        "desc": "JTBC 토크·버라이어티.",
    },
    {
        "id": "v07",
        "title": "놀라운 토요일",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 11),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 토요 음악·퀴즈 예능.",
    },
    {
        "id": "v08",
        "title": "1박 2일",
        "genre": "예능",
        "channel": "KBS2",
        "broadcaster": "KBS2 (지상파)",
        "aired_at": date(2026, 7, 5),
        "episode": "방영 중",
        "otts": [],
        "desc": "KBS2 여행·미션 예능.",
    },
    {
        "id": "v09",
        "title": "금쪽같은 내 새끼",
        "genre": "예능",
        "channel": "채널A",
        "broadcaster": "채널A (PP)",
        "aired_at": date(2026, 7, 4),
        "episode": "방영 중",
        "otts": [],
        "desc": "채널A 육아·가족 상담 예능.",
    },
    {
        "id": "v10",
        "title": "라디오스타",
        "genre": "예능",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2026, 7, 1),
        "episode": "방영 중",
        "otts": [],
        "desc": "MBC 수요 토크쇼.",
    },
    {
        "id": "v11",
        "title": "불후의 명곡",
        "genre": "예능",
        "channel": "KBS2",
        "broadcaster": "KBS2 (지상파)",
        "aired_at": date(2026, 6, 28),
        "episode": "방영 중",
        "otts": [],
        "desc": "KBS2 음악 경연 예능.",
    },
    {
        "id": "v12",
        "title": "신랑수업",
        "genre": "예능",
        "channel": "TV조선",
        "broadcaster": "TV조선 (PP)",
        "aired_at": date(2026, 6, 25),
        "episode": "방영 중",
        "otts": [],
        "desc": "TV조선 예비·신혼 부부 예능.",
    },
    {
        "id": "v13",
        "title": "나는 자연인이다",
        "genre": "예능",
        "channel": "MBN",
        "broadcaster": "MBN (PP)",
        "aired_at": date(2026, 6, 22),
        "episode": "방영 중",
        "otts": [],
        "desc": "MBN 자연인 다큐·예능.",
    },
    {
        "id": "v14",
        "title": "냉장고를 부탁해",
        "genre": "예능",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 6, 15),
        "episode": "방영 중",
        "otts": [],
        "desc": "JTBC 요리 예능.",
    },
    {
        "id": "v15",
        "title": "전국노래자랑",
        "genre": "예능",
        "channel": "KBS1",
        "broadcaster": "KBS1 (지상파)",
        "aired_at": date(2026, 6, 8),
        "episode": "방영 중",
        "otts": [],
        "desc": "KBS1 일요일 국민 노래 예능.",
        # 자동 수집이 타 프로그램(티빙·태군노래자랑)으로 오인되어 고정
        "poster_locked": True,
        "poster_url": (
            "https://phinf.pstatic.net/tvcast/20240326_238/"
            "TSkf5_1711431154087vMAPG_JPEG/2GOtb0vuXqFc.jpg"
        ),
    },
    # ========== 예능 추가 (tvN · ENA · JTBC · 지상파) ==========
    {
        "id": "v16",
        "title": "톡파원 25시",
        "genre": "예능",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 7, 20),
        "episode": "방영 중",
        "otts": [],
        "desc": "JTBC 월요 예능. 해외 현지 토크·리포트.",
    },
    {
        "id": "v17",
        "title": "쯔양몇끼",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 7, 18),
        "episode": "방영 중",
        "otts": [],
        "desc": "ENA 토요 예능. 먹방 크리에이터 쯔양의 한 끼 탐험.",
        "poster_locked": True,
        "poster_url": (
            "https://ktena.co.kr/data/file/variety/64f192ac8d12ad789d874b36756ac069_dIce69xw_e040f7de003235107812205ddeaf350fef1c8bb8.jpg"
        ),
    },
    {
        "id": "v18",
        "title": "벌거벗은 세계사",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 17),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 목요 예능. 역사 토크·강연 버라이어티.",
    },
    {
        "id": "v19",
        "title": "나는 SOLO",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 7, 16),
        "episode": "방영 중",
        "otts": [],
        "desc": "ENA 연애 리얼리티. 돌싱·비혼 남녀의 만남.",
    },
    {
        "id": "v20",
        "title": "아이돌 파견근무",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 7, 15),
        "episode": "방영 중",
        "otts": [],
        "desc": "ENA 수요 예능. 아이돌의 일반직 파견 체험.",
    },
    {
        "id": "v21",
        "title": "신발 벗고 돌싱포맨",
        "genre": "예능",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2026, 7, 14),
        "episode": "방영 중",
        "otts": [],
        "desc": "SBS 월요 예능. 돌싱 토크쇼.",
    },
    {
        "id": "v22",
        "title": "킬잇 : 스타일 크리에이터 대전쟁",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 14),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 화요 예능. 스타일 크리에이터 서바이벌.",
    },
    {
        "id": "v23",
        "title": "골 때리는 그녀들",
        "genre": "예능",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2026, 7, 13),
        "episode": "방영 중",
        "otts": [],
        "desc": "SBS 스포츠 예능. 여자 축구 리그 버라이어티.",
    },
    {
        "id": "v24",
        "title": "놀면 뭐하니?",
        "genre": "예능",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2026, 7, 11),
        "episode": "방영 중",
        "otts": [],
        "desc": "MBC 토요 예능. 유재석표 프로젝트 버라이어티.",
    },
    {
        "id": "v25",
        "title": "연애전쟁",
        "genre": "예능",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 7, 14),
        "episode": "방영 중",
        "otts": [],
        "desc": "JTBC 화요 예능. 연애 리얼리티.",
    },
    {
        "id": "v26",
        "title": "보검 매직컬",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 4, 3),
        "ended_at": date(2026, 4, 3),
        "episode": "종영",
        "otts": [],
        "desc": "tvN 힐링 예능. 박보검·이상이·곽동연 이발소. 2026.01.30~04.03 종영.",
        "poster_locked": True,
        "poster_url": (
            "https://image.starnewskorea.com/21/2026/01/2026011514095221335_1.jpg"
        ),
    },
    {
        "id": "v27",
        "title": "강연배틀쇼 사기꾼들",
        "genre": "예능",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 7, 9),
        "episode": "방영 중",
        "otts": [],
        "desc": "JTBC 목요 예능. 역사·인문 강연 배틀쇼.",
    },
    {
        "id": "v28",
        "title": "한끼합쇼",
        "genre": "예능",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2025, 8, 26),
        "episode": "종영",
        "otts": [],
        "desc": "JTBC 쿡방·힐링 예능. 2025년 종영.",
    },
    {
        "id": "v29",
        "title": "꽃보다 청춘: 리미티드 에디션",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 6, 7),
        "episode": "6부작",
        "otts": [],
        "desc": "tvN 여행 예능. 2026.05.03~06.07.",
    },
    {
        "id": "v30",
        "title": "체인지 스트릿",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 3, 27),
        "episode": "8부작",
        "otts": [],
        "desc": "ENA 금요 예능. 한일 아티스트 버스킹 버라이어티.",
    },
    {
        "id": "v31",
        "title": "방과후 태리쌤",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 4, 12),
        "episode": "8부작",
        "otts": [],
        "desc": "tvN 예능. 김태리의 방과후 연극 수업. 2026.02.22 첫방.",
    },
    {
        "id": "v32",
        "title": "길치라도 괜찮아",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 5, 30),
        "episode": "10부작",
        "otts": [],
        "desc": "ENA 토요 예능. 길치 연예인의 맞춤 여행.",
    },
    {
        "id": "v33",
        "title": "입 터지는 실험실",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 5, 16),
        "episode": "8부작",
        "otts": [],
        "desc": "ENA 토요 예능. 과학·먹방 토크쇼.",
    },
    {
        "id": "v34",
        "title": "우주떡집",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 31),
        "episode": "방영 예정 · 7/31 첫방",
        "otts": [],
        "desc": "tvN 금요 예능. 뿅뿅 지구오락실 멤버들의 떡집 영업기.",
    },
    {
        "id": "v35",
        "title": "예스맨",
        "genre": "예능",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 3, 14),
        "episode": "12부작",
        "otts": [],
        "desc": "JTBC 예능. 스포츠 스타 예능 서바이벌. 2026.01.17 첫방.",
    },
    {
        "id": "v36",
        "title": "당일배송 우리집",
        "genre": "예능",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2025, 11, 20),
        "episode": "8부작",
        "otts": [],
        "desc": "JTBC 예능. 이동주택 로컬 라이프 리얼리티. 2025 하반기.",
    },
    {
        "id": "v37",
        "title": "무쇠소녀단",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2025, 9, 15),
        "episode": "시즌",
        "otts": [],
        "desc": "tvN 운동·챌린지 예능. 시즌제 방영.",
    },
    {
        "id": "v38",
        "title": "언니네 산지직송3",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 30),
        "episode": "방영 예정 · 7/30 첫방",
        "otts": [],
        "desc": "tvN 힐링 예능 시즌3. 제철 식재료·산지 탐방.",
    },
    {
        "id": "v39",
        "title": "식스센스: 시티투어",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2025, 10, 12),
        "episode": "시즌",
        "otts": [],
        "desc": "tvN 추리·여행 예능. 가짜 찾기 시티투어.",
    },
    {
        "id": "v40",
        "title": "사장님 귀는 당나귀 귀",
        "genre": "예능",
        "channel": "KBS2",
        "broadcaster": "KBS2 (지상파)",
        "aired_at": date(2026, 7, 6),
        "episode": "방영 중",
        "otts": [],
        "desc": "KBS2 일요 예능. 직원 몰래카메라 토크.",
    },
    # ========== 예능 추가 2 (tvN·ENA·JTBC·지상파 편성) ==========
    {
        "id": "v41",
        "title": "스트릿 레스토랑 파이터",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 19),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 일요 예능. 셰프 장사 서바이벌.",
    },
    {
        "id": "v42",
        "title": "콩콩팜팜",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 17),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 금요 예능. 농장·힐링 버라이어티.",
    },
    {
        "id": "v43",
        "title": "언더커버 셰프",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 16),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 목요 예능. 셰프 잠입 관찰.",
    },
    {
        "id": "v44",
        "title": "핸썸가이즈",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2025, 10, 23),
        "ended_at": date(2025, 10, 23),
        "episode": "종영",
        "otts": [],
        "desc": "tvN 목요 예능. 시즌1 2024.12.01~2025.10.23 종영(시즌2 예정).",
    },
    {
        "id": "v45",
        "title": "동네의 명장들",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 15),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 수요 예능. 동네 장인·로컬 명인 탐방.",
    },
    {
        "id": "v46",
        "title": "이호선 상담소",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 14),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 화요 예능. 심리·관계 상담 토크.",
    },
    {
        "id": "v47",
        "title": "히든에이지",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 14),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 화요 예능. 나이 숨기기 관찰 버라이어티.",
    },
    {
        "id": "v48",
        "title": "남겨서 뭐하게",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 13),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 월요 예능. 식탁·남은 음식 토크 예능.",
    },
    {
        "id": "v49",
        "title": "프리한19",
        "genre": "예능",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 13),
        "episode": "방영 중",
        "otts": [],
        "desc": "tvN 월요 예능. 해외 현지 토크·리포트.",
    },
    {
        "id": "v50",
        "title": "디어 마이 엑스",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 7, 14),
        "episode": "종영",
        "otts": [],
        "desc": "ENA 예능. 전 연인 재회·연애 상담. (방영 종료)",
    },
    {
        "id": "v51",
        "title": "왕자와 거지",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 7, 27),
        "episode": "방영 중",
        "otts": [],
        "desc": "ENA 월요 예능. K-POP 아이돌 이집트 왕자/거지 여행. 디즈니+ 동시 공개.",
    },
    {
        "id": "v52",
        "title": "짐쌀라비움",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 8, 1),
        "episode": "방영 예정 · 8/1 첫방",
        "otts": [],
        "desc": "ENA 토요 예능. 2026.08.01 첫방.",
    },
    {
        "id": "v53",
        "title": "송영주의 재즈 포레스트",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 7, 26),
        "episode": "방영 예정 · 7/26 첫방",
        "otts": [],
        "desc": "ENA 일요 예능. 재즈·음악 토크.",
    },
    {
        "id": "v54",
        "title": "제비탐정 장성규",
        "genre": "예능",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 8, 1),
        "episode": "방영 예정 · 8/1 첫방",
        "otts": [],
        "desc": "ENA 토요 예능. 장성규의 탐정·관찰 예능.",
    },
    {
        "id": "v55",
        "title": "동상이몽 2 - 너는 내 운명",
        "genre": "예능",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2026, 7, 14),
        "episode": "방영 중",
        "otts": [],
        "desc": "SBS 화요 예능. 스타 부부 관찰 예능.",
    },
    {
        "id": "v56",
        "title": "살림하는 남자들",
        "genre": "예능",
        "channel": "KBS2",
        "broadcaster": "KBS2 (지상파)",
        "aired_at": date(2026, 7, 18),
        "episode": "방영 중",
        "otts": [],
        "desc": "KBS2 토요 예능. 살림·육아 관찰 예능.",
    },
    {
        "id": "v57",
        "title": "한문철의 블랙박스 리뷰",
        "genre": "예능",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 7, 15),
        "episode": "방영 중",
        "otts": [],
        "desc": "JTBC 수요 예능. 블랙박스 사고 분석·토크.",
    },
    # ========== 드라마 2026 (최근 방영 순) ==========
    {
        "id": "d01",
        "title": "오싹한 연애",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 7, 18),
        "ended_at": date(2026, 8, 23),
        "episode": "12부작 · 방영 중",
        "otts": [],
        "desc": "tvN 토일드라마. 2026.07.18~08.23.",
    },
    {
        "id": "d02",
        "title": "그대에게 드림",
        "genre": "드라마",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 7, 13),
        "ended_at": date(2026, 8, 18),
        "episode": "12부작 · 방영 중",
        "otts": [],
        "desc": "ENA 월화드라마. 2026.07.13~08.18.",
    },
    {
        "id": "d03",
        "title": "아파트",
        "genre": "드라마",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 7, 11),
        "ended_at": date(2026, 8, 16),
        "episode": "12부작 · 방영 중",
        "otts": [],
        "desc": "JTBC 토일드라마. 2026.07.11~08.16.",
    },
    {
        "id": "d04",
        "title": "가족관계증명서",
        "genre": "드라마",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2026, 7, 6),
        "episode": "일일 · 방영 중",
        "otts": [],
        "desc": "MBC 일일드라마. 2026.07.06 첫방.",
    },
    {
        "id": "d05",
        "title": "결혼의 완성",
        "genre": "드라마",
        "channel": "KBS2",
        "broadcaster": "KBS2 (지상파)",
        "aired_at": date(2026, 7, 4),
        "ended_at": date(2026, 8, 9),
        "episode": "12부작 · 방영 중",
        "otts": [],
        "desc": "KBS2 토일드라마. 2026.07.04~08.09.",
    },
    {
        "id": "d06",
        "title": "김부장",
        "genre": "드라마",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2026, 7, 25),
        "ended_at": date(2026, 7, 25),
        "episode": "10부작 · 종영",
        "otts": [],
        "desc": "SBS 금토드라마. 2026.06.26~07.25 종영(10화).",
    },
    {
        "id": "d07",
        "title": "내일도 출근",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 6, 22),
        "ended_at": date(2026, 7, 28),
        "episode": "12부작 · 종영",
        "otts": [],
        "desc": "tvN 월화드라마. 2026.06.22~07.28.",
    },
    {
        "id": "d08",
        "title": "신입사원 강회장",
        "genre": "드라마",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 5, 30),
        "episode": "14부작",
        "otts": [],
        "desc": "JTBC 토일드라마. 2026.05.30~07.05.",
    },
    {
        "id": "d09",
        "title": "닥터 섬보이",
        "genre": "드라마",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 6, 1),
        "episode": "12부작",
        "otts": [],
        "desc": "ENA 월화드라마. 2026.06.01~07.07.",
    },
    {
        "id": "d10",
        "title": "오십프로",
        "genre": "드라마",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2026, 5, 22),
        "episode": "12부작",
        "otts": [],
        "desc": "MBC 금토드라마. 2026.05.22~06.27.",
    },
    {
        "id": "d11",
        "title": "취사병 전설이 되다",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 5, 11),
        "episode": "12부작",
        "otts": [],
        "desc": "tvN 월화드라마. 2026.05.11~06.16.",
        # 검색 폴백 dthumb/블로그 URL이 레이아웃을 깨뜨려 공식/안정 URL 고정
        "poster_url": (
            "https://csearch-phinf.pstatic.net/20260427_289/"
            "1777268581598feg6T_JPEG/e74bc7780afe3bcc6b1a4785c2f5bafd.jpg"
        ),
    },
    {
        "id": "d12",
        "title": "21세기 대군부인",
        "genre": "드라마",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2026, 4, 10),
        "episode": "12부작",
        "otts": [],
        "desc": "MBC 금토드라마. 2026.04.10~05.16.",
    },
    {
        "id": "d13",
        "title": "모두가 자신의 무가치함과 싸우고 있다",
        "genre": "드라마",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 4, 18),
        "episode": "12부작",
        "otts": [],
        "desc": "JTBC 토일드라마. 2026.04.18~05.24.",
    },
    {
        "id": "d14",
        "title": "오늘도 매진했습니다",
        "genre": "드라마",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2026, 4, 22),
        "episode": "12부작",
        "otts": [],
        "desc": "SBS 수목드라마. 2026.04.22~05.28.",
    },
    {
        "id": "d15",
        "title": "허수아비",
        "genre": "드라마",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 4, 20),
        "episode": "12부작",
        "otts": [],
        "desc": "ENA 월화드라마. 2026.04.20~05.26.",
    },
    {
        "id": "d16",
        "title": "닥터신",
        "genre": "드라마",
        "channel": "TV조선",
        "broadcaster": "TV조선 (PP)",
        "aired_at": date(2026, 3, 14),
        "episode": "16부작",
        "otts": [],
        "desc": "TV조선 토일드라마. 2026.03.14~05.03.",
    },
    {
        "id": "d17",
        "title": "기쁜 우리 좋은 날",
        "genre": "드라마",
        "channel": "KBS1",
        "broadcaster": "KBS1 (지상파)",
        "aired_at": date(2026, 3, 30),
        "ended_at": date(2026, 9, 18),
        "episode": "일일 · 방영 중",
        "otts": [],
        "desc": "KBS1 일일드라마. 2026.03.30~09.18.",
    },
    {
        "id": "d18",
        "title": "세이렌",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 3, 2),
        "episode": "12부작",
        "otts": [],
        "desc": "tvN 월화드라마. 2026.03.02~04.07.",
        "poster_url": (
            "https://poc-cf-image.cjenm.com/public/share/contentsmng/kr/"
            "sirengalleryposter03_1770600951220.jpg"
        ),
    },
    {
        "id": "d19",
        "title": "미혼남녀의 효율적 만남",
        "genre": "드라마",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2026, 2, 28),
        "episode": "12부작",
        "otts": [],
        "desc": "JTBC 토일드라마. 2026.02.28~04.05.",
    },
    {
        "id": "d20",
        "title": "아너 : 그녀들의 법정",
        "genre": "드라마",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2026, 2, 2),
        "episode": "12부작",
        "otts": [],
        "desc": "ENA 월화드라마. 2026.02.02~03.10.",
    },
    {
        "id": "d21",
        "title": "아기가 생겼어요",
        "genre": "드라마",
        "channel": "채널A",
        "broadcaster": "채널A (PP)",
        "aired_at": date(2026, 1, 17),
        "episode": "12부작",
        "otts": [],
        "desc": "채널A 토일드라마. 2026.01.17~02.22.",
    },
    {
        "id": "d22",
        "title": "오늘부터 인간입니다만",
        "genre": "드라마",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2026, 1, 16),
        "episode": "12부작",
        "otts": [],
        "desc": "SBS 금토드라마. 2026.01.16~02.28.",
    },
    {
        "id": "d23",
        "title": "스프링 피버",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2026, 1, 5),
        "episode": "12부작",
        "otts": [],
        "desc": "tvN 월화드라마. 2026.01.05~02.10.",
    },
    {
        "id": "d24",
        "title": "판사 이한영",
        "genre": "드라마",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2026, 1, 2),
        "episode": "14부작",
        "otts": [],
        "desc": "MBC 금토드라마. 2026.01.02~02.14.",
    },
    {
        "id": "d25",
        "title": "은애하는 도적님아",
        "genre": "드라마",
        "channel": "KBS2",
        "broadcaster": "KBS2 (지상파)",
        "aired_at": date(2026, 1, 3),
        "episode": "16부작",
        "otts": [],
        "desc": "KBS2 토일드라마. 2026.01.03~02.22.",
    },
    # ========== 드라마 2025 ==========
    {
        "id": "d26",
        "title": "모범택시 3",
        "genre": "드라마",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2025, 11, 21),
        "episode": "16부작",
        "otts": [],
        "desc": "SBS 금토드라마. 2025.11.21~2026.01.10.",
    },
    {
        "id": "d27",
        "title": "프로보노",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2025, 12, 6),
        "episode": "12부작",
        "otts": [],
        "desc": "tvN 토일드라마. 2025.12.06~2026.01.11.",
    },
    {
        "id": "d28",
        "title": "경도를 기다리며",
        "genre": "드라마",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2025, 12, 6),
        "episode": "16부작",
        "otts": [],
        "desc": "JTBC 토일드라마. 2025.12.06~2026.01.25.",
    },
    {
        "id": "d29",
        "title": "퍼스트레이디",
        "genre": "드라마",
        "channel": "MBN",
        "broadcaster": "MBN (PP)",
        "aired_at": date(2025, 9, 24),
        "episode": "12부작",
        "otts": [],
        "desc": "MBN 수목드라마. 2025.09.24~10.30.",
    },
    {
        "id": "d30",
        "title": "컨피던스맨 KR",
        "genre": "드라마",
        "channel": "TV조선",
        "broadcaster": "TV조선 (PP)",
        "aired_at": date(2025, 9, 6),
        "episode": "12부작",
        "otts": [],
        "desc": "TV조선 토일드라마. 2025.09.06~10.12.",
    },
    {
        "id": "d31",
        "title": "폭군의 셰프",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2025, 8, 23),
        "episode": "12부작",
        "otts": [],
        "desc": "tvN 토일드라마. 2025.08.23~09.28.",
    },
    {
        "id": "d32",
        "title": "트라이: 우리는 기적이 된다",
        "genre": "드라마",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2025, 7, 25),
        "episode": "12부작",
        "otts": [],
        "desc": "SBS 금토드라마. 2025.07.25~08.30.",
    },
    {
        "id": "d33",
        "title": "견우와 선녀",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2025, 6, 23),
        "episode": "12부작",
        "otts": [],
        "desc": "tvN 월화드라마. 2025.06.23~07.29.",
    },
    {
        "id": "d34",
        "title": "살롱 드 홈즈",
        "genre": "드라마",
        "channel": "ENA",
        "broadcaster": "ENA (PP)",
        "aired_at": date(2025, 6, 16),
        "episode": "10부작",
        "otts": [],
        "desc": "ENA 월화드라마. 2025.06.16~07.15.",
    },
    {
        "id": "d35",
        "title": "굿보이",
        "genre": "드라마",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2025, 5, 31),
        "episode": "16부작",
        "otts": [],
        "desc": "JTBC 토일드라마. 2025.05.31~07.20.",
    },
    {
        "id": "d36",
        "title": "천국보다 아름다운",
        "genre": "드라마",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2025, 4, 19),
        "episode": "12부작",
        "otts": [],
        "desc": "JTBC 토일드라마. 2025.04.19~05.25.",
    },
    {
        "id": "d37",
        "title": "언젠가는 슬기로울 전공의생활",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2025, 4, 12),
        "episode": "12부작",
        "otts": [],
        "desc": "tvN 토일드라마. 2025.04.12~05.18.",
    },
    {
        "id": "d38",
        "title": "바니와 오빠들",
        "genre": "드라마",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2025, 4, 11),
        "episode": "12부작",
        "otts": [],
        "desc": "MBC 금토드라마. 2025.04.11~05.17.",
    },
    {
        "id": "d39",
        "title": "협상의 기술",
        "genre": "드라마",
        "channel": "JTBC",
        "broadcaster": "JTBC (PP)",
        "aired_at": date(2025, 3, 8),
        "episode": "12부작",
        "otts": [],
        "desc": "JTBC 토일드라마. 2025.03.08~04.13.",
    },
    {
        "id": "d40",
        "title": "감자연구소",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2025, 3, 1),
        "episode": "12부작",
        "otts": [],
        "desc": "tvN 토일드라마. 2025.03.01~04.06.",
    },
    {
        "id": "d41",
        "title": "언더커버 하이스쿨",
        "genre": "드라마",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2025, 2, 21),
        "episode": "12부작",
        "otts": [],
        "desc": "MBC 금토드라마. 2025.02.21~03.29.",
    },
    {
        "id": "d42",
        "title": "마녀",
        "genre": "드라마",
        "channel": "채널A",
        "broadcaster": "채널A (PP)",
        "aired_at": date(2025, 2, 15),
        "episode": "10부작",
        "otts": [],
        "desc": "채널A 토일드라마. 2025.02.15~03.16.",
    },
    {
        "id": "d43",
        "title": "모텔 캘리포니아",
        "genre": "드라마",
        "channel": "MBC",
        "broadcaster": "MBC (지상파)",
        "aired_at": date(2025, 1, 10),
        "episode": "12부작",
        "otts": [],
        "desc": "MBC 금토드라마. 2025.01.10~02.15.",
    },
    {
        "id": "d44",
        "title": "별들에게 물어봐",
        "genre": "드라마",
        "channel": "tvN",
        "broadcaster": "tvN (PP)",
        "aired_at": date(2025, 1, 4),
        "episode": "16부작",
        "otts": [],
        "desc": "tvN 토일드라마. 2025.01.04~02.23.",
    },
    {
        "id": "d45",
        "title": "나의 완벽한 비서",
        "genre": "드라마",
        "channel": "SBS",
        "broadcaster": "SBS (지상파)",
        "aired_at": date(2025, 1, 3),
        "episode": "12부작",
        "otts": [],
        "desc": "SBS 금토드라마. 2025.01.03~02.14.",
    },
]


def get_sorted_contents(genre_filter: str | None = None) -> list[dict]:
    """최근 방영일 기준 내림차순. 2025·2026년 방영분만."""
    items = [c for c in CONTENTS if c["aired_at"].year in (2025, 2026)]
    if genre_filter and genre_filter != "전체":
        items = [c for c in items if c["genre"] == genre_filter]
    return sorted(items, key=lambda x: x["aired_at"], reverse=True)


def get_content_by_id(content_id: str) -> dict | None:
    for c in CONTENTS:
        if c["id"] == content_id:
            return c
    return None


def palette_for(index: int) -> tuple[str, str]:
    return _PALETTES[index % len(_PALETTES)]


def channel_summary() -> dict[str, int]:
    """채널별 콘텐츠 수 (검수용)."""
    summary: dict[str, int] = {}
    for c in CONTENTS:
        summary[c["channel"]] = summary.get(c["channel"], 0) + 1
    return summary
